# permissions for end users to edit ownedlabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ownedlabels-editor-role
rules:
- apiGroups:
  - node-labels.openshift.io
  resources:
  - ownedlabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - node-labels.openshift.io
  resources:
  - ownedlabels/status
  verbs:
  - get
