apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: OpenShift Optional
  name: node-label-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Labels is the Schema for the labels API. Labels define which labels should be added to which nodes.
      displayName: Labels
      kind: Labels
      name: labels.node-labels.openshift.io
      version: v1beta1
    - description: OwnedLabels is the Schema for the ownedlabels API. They define which node labels are owned by this operator and can safely be removed in case no label rule matches anymore.
      displayName: Owned Labels
      kind: OwnedLabels
      name: ownedlabels.node-labels.openshift.io
      version: v1beta1
  description: Operator for labeling nodes based on their names
  displayName: Node Label Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - node
  - labels
  links:
  - name: Node Label Operator
    url: https://github.com/openshift-kni/node-label-operator
  maintainers:
  - email: kni-lifecycle-team@redhat.com
    name: KNI Lifecycle Team
  maturity: alpha
  provider:
    name: Red Hat
    url: https://www.redhat.com
  version: 0.0.0
